run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  funlen:
    lines: 100
    statements: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    rules:
      main:
        allow:
          # Standard Go imports
          - "context"
          - "testing"
          - "time"
          # OpenTelemetry Collector imports
          - "go.opentelemetry.io/collector/component"
          - "go.opentelemetry.io/collector/connector"
          - "go.opentelemetry.io/collector/connector/xconnector"
          - "go.opentelemetry.io/collector/consumer"
          - "go.opentelemetry.io/collector/pdata/pprofile"
          - "go.opentelemetry.io/collector/pdata/pmetric"
          - "go.opentelemetry.io/collector/pdata/pcommon"
          - "go.uber.org/zap"
          # Testing libraries
          - "github.com/stretchr/testify/assert"
          - "github.com/stretchr/testify/require"
          # Internal packages
          - "github.com/henrikrexed/profiletoMetrics/pkg/profiletometrics"
          - "github.com/henrikrexed/profiletoMetrics/testdata"

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gocyclo
    - path: testdata/
      linters:
        - mnd
        - funlen
        - goconst
        - gocyclo
    - path: examples/
      linters:
        - mnd
        - funlen
        - goconst
        - gocyclo