apiVersion: v1
kind: Namespace
metadata:
  name: otel-collector
  labels:
    name: otel-collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: profile-metrics
  labels:
    name: profile-metrics
    app.kubernetes.io/name: profile-metrics
    app.kubernetes.io/component: observability
