apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-headless
  namespace: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
