# Simple OpenTelemetry Collector Configuration with Profile to Metrics Connector
# This is a minimal configuration for testing and development

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

connectors:
  profiletometrics:
    metrics:
      cpu:
        enabled: true
        name: "profile_cpu_time_seconds"
        unit: "s"
      memory:
        enabled: true
        name: "profile_memory_allocation_bytes"
        unit: "bytes"
    
    attributes:
      - name: "process_name"
        value: "test_process"
        type: "literal"
      - name: "service_name"
        value: "test_service"
        type: "literal"
    
    process_filter:
      enabled: true
      pattern: ".*"
    
    thread_filter:
      enabled: false
      pattern: ""

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://localhost:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      connectors: [profiletometrics]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
