name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write
  security-events: write

env:
  GO_VERSION: '1.24'
  REGISTRY: ghcr.io
  IMAGE_NAME: henrikrexed/otel-collector-profilemetrics
  DOCKER_IMAGE: ghcr.io/henrikrexed/otel-collector-profilemetrics
  DOCKER_TAG: latest

jobs:
  # Build and Test Job
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']
        platform: [linux/amd64, linux/arm64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run static analysis
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...

    - name: Run tests
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Generate coverage report
      run: |
        go tool cover -html=coverage.out -o coverage.html

    - name: Check test coverage threshold
      run: |
        echo "Checking test coverage threshold..."
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Current coverage: $COVERAGE%"
        COVERAGE_THRESHOLD=60.0
        if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
          echo "ERROR: Test coverage ($COVERAGE%) is below required threshold ($COVERAGE_THRESHOLD%)"
          echo "Please add more tests to increase coverage"
          exit 1
        else
          echo "✓ Test coverage ($COVERAGE%) meets required threshold ($COVERAGE_THRESHOLD%)"
        fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  # Security Scanning Job
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install Gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run Gosec Security Scanner
      run: |
        gosec -fmt sarif -out gosec.sarif ./...
      continue-on-error: true

    - name: Check if Gosec results exist
      id: gosec-check
      run: |
        if [ -f "gosec.sarif" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✓ Gosec results file found"
          echo "File size: $(wc -c < gosec.sarif) bytes"
          echo "First few lines:"
          head -5 gosec.sarif
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "✗ Gosec results file not found"
        fi

    - name: Upload Gosec results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.gosec-check.outputs.exists == 'true'
      with:
        sarif_file: gosec.sarif
      continue-on-error: true

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true

    - name: Check if Trivy results exist
      id: trivy-check
      run: |
        if [ -f "trivy-results.sarif" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✓ Trivy results file found"
          echo "File size: $(wc -c < trivy-results.sarif) bytes"
          echo "First few lines:"
          head -5 trivy-results.sarif
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "✗ Trivy results file not found"
        fi

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.trivy-check.outputs.exists == 'true'
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

  # OSS Scorecard Job
  oss-scorecard:
    name: OSS Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Run OSS Scorecard
      uses: ossf/scorecard-action@v2.3.1
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload OSS Scorecard results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif
      continue-on-error: true

  # SBOM Generation Job
  sbom-generation:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.event_name == 'push' || github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft version

    - name: Generate Go module SBOM
      run: |
        syft packages . -o spdx-json=go-sbom.spdx.json
        syft packages . -o cyclonedx-json=go-sbom.cyclonedx.json
        syft packages . -o table=go-sbom.txt

    - name: Upload Go SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-sbom
        path: |
          go-sbom.spdx.json
          go-sbom.cyclonedx.json
          go-sbom.txt

  # Docker Build and Test Job
  docker-build:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    needs: [build-and-test, sbom-generation]
    if: github.event_name == 'push' || github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{version}}-{{commit}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image with SBOM
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        sbom: true
        provenance: true
        attests: sbom=true,provenance=true

    - name: Test Docker image
      run: |
        # Test help command
        docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} --help
        
        # Test configuration validation
        docker run --rm \
          -v $(pwd)/examples/simple-config.yaml:/etc/otelcol/config.yaml \
          ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} \
          --config=/etc/otelcol/config.yaml --feature-gates=+service.profilesSupport --dry-run
        
        # Test components command
        docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} components

    - name: Generate Docker image SBOM
      run: |
        # Install Syft
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        
        # Generate SBOM for the built image
        syft ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -o spdx-json=docker-sbom.spdx.json
        syft ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -o cyclonedx-json=docker-sbom.cyclonedx.json
        syft ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -o table=docker-sbom.txt

    - name: Upload Docker SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-sbom
        path: |
          docker-sbom.spdx.json
          docker-sbom.cyclonedx.json
          docker-sbom.txt

  # Integration Tests Job
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'push' || github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run integration tests
      run: |
        # Test the Docker image with debug configuration
        docker run -d --name otelcol-test \
          -p 4317:4317 \
          -p 4318:4318 \
          -v $(pwd)/examples/working-debug-config.yaml:/etc/otelcol/config.yaml \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
          --config=/etc/otelcol/config.yaml --feature-gates=+service.profilesSupport
        
        # Wait for collector to start
        sleep 10
        
        # Test OTLP profiles endpoint
        curl -X POST http://localhost:4318/v1/profiles \
          -H "Content-Type: application/json" \
          -d '{
            "resourceProfiles": [{
              "resource": {
                "attributes": [{
                  "key": "service.name",
                  "value": {"stringValue": "test-service"}
                }]
              },
              "scopeProfiles": [{
                "scope": {"name": "test-scope"},
                "profiles": [{
                  "profileId": "12345678901234567890123456789012",
                  "name": "test-profile",
                  "startTimeUnixNano": "1640995200000000000",
                  "endTimeUnixNano": "1640995201000000000"
                }]
              }]
            }]
          }'
        
        # Check logs for debug output
        docker logs otelcol-test
        
        # Cleanup
        docker stop otelcol-test
        docker rm otelcol-test

  # Code Quality Job
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m --verbose
        working-directory: .

    - name: Run ineffassign
      run: |
        go install github.com/gordonklaus/ineffassign@latest
        ineffassign ./...

    - name: Run misspell
      run: |
        go install github.com/client9/misspell/cmd/misspell@latest
        misspell -error .

    - name: Run gocyclo
      run: |
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        gocyclo -over 15 .

  # Documentation Job
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check documentation
      run: |
        go doc -all ./pkg/... > /dev/null
        go doc -all . > /dev/null
        echo "Documentation check passed"

    - name: Generate documentation
      run: |
        mkdir -p docs/api
        go doc -all ./pkg/... > docs/api/pkg.md
        go doc -all . > docs/api/connector.md
        echo "API documentation generated"

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/

  # Release Job
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan, oss-scorecard, docker-build, integration-tests]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: |
          ## Changes in this Release
          
          ### Features
          - Profile to Metrics connector implementation
          - Debug logging support
          - Docker image with custom collector
          
          ### Security
          - Security scanning with Gosec and Trivy
          - OSS Scorecard compliance
          
          ### Quality
          - Comprehensive test coverage
          - Code quality checks
          - Integration testing
        draft: false
        prerelease: false
